monitor=DP-2,1920x1080@60,0x0,1
monitor=HDMI-A-1,preferred,-1920x0,1
monitor=HDMI-A-2,1920x1080@60,1920x0,1

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps
    kb_rules =
}

# Monitor1
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
# Monitor2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
# Monitor3
workspace = 7, monitor:HDMI-A-2
workspace = 8, monitor:HDMI-A-2
workspace = 9, monitor:HDMI-A-2
